language: php

os:
  - linux

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

jobs:
  fast_finish: true
  include:
    - php: 7.3
      env:
        - COMPOSER_ARGUMENTS=--prefer-lowest
    - php: 7.3
      env:
        - EXECUTE_TEST_COVERALLS=true
    - php: 8.0
      env:
        - EXECUTE_CS_CHECK=true

install:
  - travis_retry composer update --no-interaction $COMPOSER_ARGUMENTS
  - composer info -i

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then XDEBUG_MODE=coverage composer test-coverage -- --colors=always; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then composer test -- --colors=always; fi

  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then PHP_CS_FIXER_IGNORE_ENV=true composer cs-check -- --ansi; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then
    travis_retry wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar;
    chmod +x php-coveralls.phar;
    travis_retry php php-coveralls.phar --verbose;
    fi
