<?php

namespace Ibercheck\Api\ApiProblem;

interface ApiProblemInterface
{
    /**
     * A short, human-readable summary of the problem type.
     */
    public function getTitle(): string;

    /**
     * The HTTP status code generated by the origin server for this occurrence of the problem.
     */
    public function getStatus(): int;

    /**
     * An absolute URI that identifies the problem type.
     */
    public function getType(): string;

    /**
     * An human readable explanation specific to this occurrence of the problem.
     *
     * @return string|array
     */
    public function getDetail();
}
